sudo: required
services:
  - docker
before_install:
  - docker build -t bobstrange/sandbox -f docker/frontend/Dockerfile.dev ./docker/frontend
script:
  - docker run -e CI=true bobstrange/sandbox npm run test

