version: '3'
services:
  nginx:
    image: nginx
    restart: always
    ports:
      - '8080:80'
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
  app:
    build: .
    volumes:
      - /app/node_modules
      - /app/dist
      - ./:/app

