version: '3'
services:
  db:
    image: mongo:4.2
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: user
      MONGO_INITDB_ROOT_PASSWORD: password
    ports:
      - 37017:27017
    volumes:
      - ./db:/data/db
