version = 0.1
[stg]
[stg.deploy]
[stg.deploy.parameters]
stack_name = "eiger-bob-test"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-a56irdycinex"
s3_prefix = "eiger-bob-test"
region = "ap-northeast-1"
profile = "sherpa-old"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
